import MainNav from "@/components/MainNav";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="flex items-start gap-8">
          <MainNav />
          <div className=" pt-8 pr-8 flex flex-col gap-8 w-full h-screen ">
            <div className=" flex justify-end items-center w-full">
              <img
                src="/profile.png"
                alt=""
                className=" rounded-full w-[60px] h-[60px] cursor-pointer"
              />
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
